name: application
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dropdown_search: ^5.0.6
  flutter_local_notifications: ^16.2.0
  timezone: ^0.9.2

  cupertino_icons: ^1.0.2
  http: ^1.1.2 
  date_time_picker: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  csv: ^5.1.1
  file_picker: ^6.1.1
  mysql1: ^0.20.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    
  
 